- .github/workflows/ci.yml
Maybe this fixes the caching thing?
> ci: Use ~ instead of $HOME.

- .github/workflows/ci.yml
I wonder if using the custom ./bazel script is messing things up.
Attempting fix for #16
> ci: Fix build caching maybe.

- .github/workflows/ci.yml
> ci: Turn on logging for Bazel rebuilds.

- scip_indexer/SCIPIndexer.cc
- test/scip/testdata/non_existent.rb
- test/scip/testdata/non_existent.snapshot.rb
Ran into this while trying to reduce a crash on indexing Homebrew/brew.
Added test.
> fix: Fix crash on having direct root references.

- .github/workflows/ci.yml
- scip-ruby.md
- test/scip/repos/BUILD
- test/scip/repos/brew-3.5.7.patch
- test/scip/repos/index_oss_repo.sh
- test/scip/repos/scip_repos_test.bzl
Preventing future regressions.
n/a
> test: Index Homebrew for CI testing.

- .github/workflows/lint.yml
Seems simpler than running the `tools/scripts`.
n/a
> ci: Add lint action.

- .github/workflows/ci.yml
Try to fix #16 
Johnson's CI cache hits: no more tears.
> ci: Try fix GitHub Actions caching?

- .buildkite/pipeline.yaml
- .buildkite/test-indexer.sh
I'm tired of the caching not working properly. 😩
n/a
> ci: Save Bazel execution logs for debugging.

- .buildkite/pipeline.yaml
- .buildkite/test-indexer.sh
I don't understand why there aren't prebuilt packages available, but let's work around that with this for now.
See if caching works later
> ci: Cache Ruby in Buildkite.

- .github/workflows/build_gems.yml
- .github/workflows/ci.yml
- docs/scip-ruby/CONTRIBUTING.md
- docs/scip-ruby/DESIGN.md
- gems/scip-ruby/BUILD
- gems/scip-ruby/build_gems.bzl
- gems/scip-ruby/install_standalone_ruby.sh
- test/scip/repos/bundle_cache.sh
- test/scip/repos/index_gem.sh
- test/scip/repos/scip_repos_test.bzl
- test/scip/repos/shopify-api-ruby-v11.1.0-darwin.patch
- test/scip/repos/shopify-api-ruby-v11.1.0-linux.patch
Ran into a crash inside Bundler. 😫
I finally thought I had a solution that would work, but no.
💀
> build: Try to fix repo tests unsuccessfully.

- README.md
Easier to understand what this does.
n/a
> docs: Add Find references image to README.

- core/Symbols.h
- scip_indexer/SCIPIndexer.cc
Cut a release.
Going to manually run the build gems action.
> fix: Compilation errors in release builds.

- scip_indexer/SCIPIndexer.cc
It was more confusing earlier.
I should probably add some tests for this... ☹️
>  fix: Use consistent logic for use before def. 

- cfg/CFG.h
> docs: Add couple of doc comments for debugging methods.

- test/scip/testdata/method_inheritance.rb
- test/scip/testdata/method_inheritance.snapshot.rb
> test: Add one more test for method inheritance.

- scip_indexer/Debug.h
Cut a release...
Will test gem build manually.
> ci: Fix macro in release builds.

- CHANGELOG.md
- README.md
- scip_indexer/SCIPIndexer.cc
> docs: Add CHANGELOG entry for v0.2.0 and update README.

- .github/workflows/ci.yml
- docs/scip-ruby/CONTRIBUTING.md
- test/scip/BUILD
- test/scip/scip_test.bzl
- test/scip/testdata/multigem/downstream.rb
- test/scip/testdata/multigem/gem-map/gem-map.json
- test/scip/testdata/multigem/upstream.rb
- test/scip_test_runner.cc
This also enables multi-file tests with nested directories,
which I'd like to have for multi-gem tests in #149.
n/a
> cleanup: Simplify test build & runner logic.

- common/common.cc
> cleanup: Replace use of getcwd with current_path.

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
> docs: Add CHANGELOG entry for v0.3.1

- scip_indexer/autoindex.sh
> autoindex: Simplify logic for adding source to Gemfile.

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
Cut v0.3.2 release with updated Docker image.
n/a
> docs: Add CHANGELOG entry for v0.3.2

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
Publish a new release soon.
n/a
> docs: Add CHANGELOG entry for v0.3.4

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
> docs: Add CHANGELOG entry for v0.3.5

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
> docs: Add CHANGELOG entry for v0.3.6

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
Publish new release with #190
n/a
> docs: Add CHANGELOG entry for v0.3.7

- scip_indexer/SCIPIndexer.cc
Fixes #195 and reduces debug log spew
We don't have a minimal test case yet.
> fix: Fix ENFORCE due to incorrect empty type folding

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
> docs: Add CHANGELOG entry for v0.3.8

- CHANGELOG.md
- Dockerfile.autoindex
- scip_indexer/SCIPIndexer.cc
Publish new release with latest changes from upstream Sorbet
n/a
> docs: Add CHANGELOG entry for v0.3.9
