scip_indexer/SCIPIndexer.cc, test/scip/testdata/syntax.rb.snapshot, test/scip_test_runner.cc
This helps reduce confusion between seemingly duplicate references
(one of them is a write). It also surfaces the bit that we aren't handling
writes for arrays and hashes correctly.
Updated snapshot.
=> test: Mark write accesses separately.

scip_indexer/SCIPIndexer.cc, test/scip/scip_test.bzl, test/scip/testdata/for.rb, test/scip/testdata/for.snapshot.rb
The variable bound the the loop 'just works', but we need some
extra fixes to make sure we don't emit needless refs/defs for
temporaries.
=> feat: Add support for for loops.

core/LocOffsets.h, scip_indexer/SCIPIndexer.cc, test/scip/testdata/loops_and_conditionals.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb, test/scip/testdata/s.rb, test/scip/testdata/s.snapshot.rb
See individual commits for details.
Progress towards #1 
=> feat: Add support for loops and conditionals

scip_indexer/SCIPIndexer.cc, test/scip/testdata/args.snapshot.rb, test/scip/testdata/arrays.snapshot.rb, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/for.snapshot.rb, test/scip/testdata/functions.snapshot.rb, test/scip/testdata/hashes.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb
Should've fixed this earlier; it is needlessly polluting the snapshots.
=> fix: Stop emitting definitions for <static-init>.

scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPUtils.cc, test/scip/testdata/args.snapshot.rb, test/scip/testdata/arrays.snapshot.rb, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/for.snapshot.rb, test/scip/testdata/functions.snapshot.rb, test/scip/testdata/hashes.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb
Fixes issue #14.
Updated existing tests.
=> fix: Emit qualified names for symbols

cfg/builder/builder.h, cfg/builder/builder_entry.cc, cfg/builder/builder_walk.cc, scip_indexer/SCIPIndexer.cc, test/scip/testdata/classes.rb, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/fields_and_attrs.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/for.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb, test/scip_test_runner.cc
This patch rewrites the handling for aliases to largely consistently
handle classes etc., instead of having one-off hacks.
(TBF, I didn't fully understand how aliases worked earlier.)
Thanks to this, constants also seem to mostly work now.
Progress towards #1.
Added some tests for instance variables.
TODO:
=> feat: Add support for fields, attribute accessors and funcs in method calls

scip_indexer/SCIPIndexer.cc, test/scip/testdata/gem_metadata.rb, test/scip/testdata/gem_metadata.snapshot.rb, test/scip_test_runner.cc
This allows us to upload an accurate index by at least manually passing this flag.
In the future, we will likely want to infer the configuration without the flag,
but it will be useful to have an override, e.g. for testing.
=> feat: Add flag to indicate gem name + version.

scip_indexer/SCIPIndexer.cc
The multiline case should normally be fine (albeit, it's a little surprising, so potentially a bug).
The other error message was not super helpful, so improve that.
Both of these were triggered when trying to index Homebrew/brew.
n/a
=> cleanup: Remove needless enforce + improve enforce error.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/args.rb, test/scip/testdata/args.snapshot.rb
Without this patch, we trigger the ENFORCE where multiple local variables
share the same source location for their definition.
Progress towards #1.
=> fix: Fix crash with default arguments.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/types.rb, test/scip/testdata/types.snapshot.rb
Bugs are bad lah.
Added test case.
=> fix: Fix bug where LocOffsets in AliasMap were incorrect.

scip_indexer/SCIPIndexer.cc
Hard-coding the root stops `scip snapshot` from working.
Manually tested against Homebrew/brew.
=> fix: Use CWD as project_root instead of hard-coding it.

scip-ruby.md
Nice to have because I will forget some of this.
n/a
=> docs: Add docs for manual testing + submitting PRs.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/types.rb, test/scip/testdata/types.snapshot.rb
This ENFORCE was triggered when trying to index Homebrew/brew.
=> fix: Fix crash with duplicate alias locs.

scip_indexer/SCIPIndexer.cc
This seems unnecessary and confusing.
n/a, SymbolInformation isn't shown in the snapshot output (maybe it should be though?)
=> fix: Don't emit SymbolInformation for local defs.

scip_indexer/BUILD, scip_indexer/SCIPIndexer.cc, test/scip/testdata/hoverdocs.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip_test_runner.cc
Progress towards #1. There are still some gaps such as #33 and #34.
=> feat: Add support for hover docs.

test/scip/testdata/args.snapshot.rb, test/scip/testdata/arrays.snapshot.rb, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/for.snapshot.rb, test/scip/testdata/functions.snapshot.rb, test/scip/testdata/gem_metadata.snapshot.rb, test/scip/testdata/hashes.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb, test/scip/testdata/types.snapshot.rb, test/scip_test_runner.cc
This should be easier to read.
=> cleanup: Make snapshot output less noisy.

test/scip/testdata/hoverdocs.rb, test/scip/testdata/hoverdocs.snapshot.rb
I keep forgetting that this is needed.
n/a
=> test: Add missing extend T::Sig.

scip-ruby.md
I'll probably forget to mention it to someone contributing.
n/a
=> docs: Add note about adding .snapshot.rb files manually.

test/helpers/expectations.cc, test/helpers/expectations.h, test/scip/BUILD, test/scip/scip_test.bzl, test/scip/testdata/multifile/basic/def_class1.rb, test/scip/testdata/multifile/basic/def_class1.snapshot.rb, test/scip/testdata/multifile/basic/use_class1.rb, test/scip/testdata/multifile/basic/use_class1.snapshot.rb, test/scip_test_runner.cc
This is mainly a foundational PR. More complex testing stuff will be in follow-up PRs.
=> test: Add support for multifile tests.

scip_indexer/SCIPIndexer.cc, test/scip_test_runner.cc
The `name@version` was acting as a group not an argument placeholder.
n/a
=> cleanup: Minor changes to --help output.

.github/workflows/release.yml
=> ci: Add GitHub Action for cutting releases.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/multifile/typed-false-mix/def_untyped.rb, test/scip/testdata/multifile/typed-false-mix/def_untyped.snapshot.rb, test/scip/testdata/multifile/typed-false-mix/use_untyped.rb, test/scip/testdata/multifile/typed-false-mix/use_untyped.snapshot.rb
Encountered when indexing Homebrew/brew.
Crash == bad.
Added test.
=> fix: Fix crash when inheriting from class defined in untyped code.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/implicit_super_arg.rb, test/scip/testdata/implicit_super_arg.snapshot.rb
Triggered when indexing Homebrew/brew.
=> fix: Fix ENFORCE triggered by implicit argument passing.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/def_delegator.rb, test/scip/testdata/def_delegator.snapshot.rb
Ran into this while indexing Homebrew/brew.
=> fix: Fix ENFORCE hit due to definition for internal symbol.

scip-ruby.md
For when I will have forgotten where the binary is.
n/a
=> docs: Add note about debugging with LLDB.

scip_indexer/SCIPIndexer.cc
We're passing empty types in some situations, this should make debugging easier.
n/a
=> cleanup: Add ENFORCE for checking type in hover doc.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/freeze_constants.rb, test/scip/testdata/freeze_constants.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/type_change.rb, test/scip/testdata/type_change.snapshot.rb, test/scip_test_runner.cc
It is not fully correct yet, because in some cases we emit
the SymbolInfo.documentation with wrong type information, and
subsequently add override_documentation with the right type
information.
For such situations, we should overwrite the original docs
instead or not emit it in the first place.
I will fix that in a subsequent PR. https://github.com/sourcegraph/scip-ruby/issues/51
Fixes a crash while indexing Homebrew/brew.
=> feat: Add override_documentation for type changes.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/inheritance.rb, test/scip/testdata/inheritance.snapshot.rb
Triggered when trying to index Homebrew/brew.
Bug fix.
=> fix: Fix ENFORCE by allowing declared non-static fields.

scip_indexer/SCIPIndexer.cc
For some reason, I haven't been able to reproduce this
by creating similar files but with slightly different
function and variable names (a, b, c etc.). I don't
quite understand why that didn't work, but this reliably
fixes some crashes when indexing Homebrew/brew.
Crash = bad.
Manually tested against Homebrew/brew.
=> fix: Fix ENFORCE hit due to cache reuse across functions.

scip_indexer/SCIPIndexer.cc
It was a little confusing that it always succeeded.
=> cleanup: Simplify return type of saveReferenceImpl.

.github/workflows/release-template.md, .github/workflows/release.yml, scip-ruby.md
This will use the cache for faster builds. IDK if there's a good way to avoid the duplication related to caching steps between the workflows...
Will try to publish a release after this.
=> ci: Clean up CI workflow for releases.

cfg/Instructions.h, scip-ruby.md
Unbreak the build so that we can use the release config in the release workflow.
Ran the release build locally. It seems wasteful to do a release build in CI because we don't have that many tests and the build becomes more time-consuming + will occupy more cache space.
=> cfg: Fix type sizes in release build.

.github/workflows/release-template.md
People don't normally have the kernel versions top-of-mind.
n/a
=> ci: Add OS key for Darwin -> macOS in release template.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/freeze_constants.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/multifile/basic/use_class1.snapshot.rb, test/scip/testdata/type_change.snapshot.rb, test/scip/testdata/type_docs.rb, test/scip/testdata/type_docs.snapshot.rb
Make output slightly more legible.
Updated tests.
=> hoverdocs: Don't use T.let syntax for hoverdocs.

docs/scip-ruby/CONTRIBUTING.md
Mistakes in heading structure, better highlighting.
n/a
=> docs: Fix headings, code snippet languages.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/rescue.rb, test/scip/testdata/rescue.snapshot.rb
=>  fix: Emit reference for rescued bindings. 

README.md
I got an error with the old command
```
❯ OS="$(uname -s | tr '[:upper:]' '[:lower:]')" RELEASE_URL="https://github.com/sourcegraph/scip-ruby/releases/latest/download" curl -L "$RELEASE_URL/scip-ruby-x86_64-$OS" -o scip-ruby && chmod +x scip-ruby
curl: (3) URL using bad/illegal format or missing URL
```
Inlining the variables made the download succeed
=> Documentation: inline variables for `curl` command

scip_indexer/BUILD, scip_indexer/SCIPUtils.cc, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/def_delegator.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/implicit_super_arg.snapshot.rb, test/scip/testdata/inheritance.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb, test/scip/testdata/multifile/basic/def_class1.snapshot.rb, test/scip/testdata/type_change.snapshot.rb, test/scip/testdata/type_docs.snapshot.rb, test/scip/testdata/types.snapshot.rb
Fixes issue https://github.com/sourcegraph/scip-ruby/issues/89
Updated existing tests
=> fix: Escape special characters in SCIP symbols.

docs/scip-ruby/CONTRIBUTING.md, tools/scripts/comby-rewrites.toml, tools/scripts/simplify-cxx-fqns.py
Looking at fully qualified symbols is exhausting.
Works on my machine. ™️
=> debug: Add utility script for more readable stack traces.

cfg/CFG.cc, core/GlobalState.cc, core/GlobalState.h, core/Symbols.cc, core/Symbols.h, namer/namer.cc, resolver/resolver.cc, scip_indexer/SCIPIndexer.cc, test/hello-test.cc
Fixes a crash when indexing Homebrew/brew, where we were running into
situations where we'd end up having a LocOffset for a nameLoc,
and it'd be unclear which file it corresponded to. Trying to
recover that information after the fact, such as from the method's
Loc field, seemed unreliable, so I've chosen to carry a Loc instead.
Manually tested by indexing Hombrew/brew.
=> fix: Propagate Locs instead of LocOffsets.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/blocks_lambdas_procs.rb, test/scip/testdata/blocks_lambdas_procs.snapshot.rb
Better coverage / avoid regressions.
=> test: Add tests for blocks, lambdas and procs.

scip_indexer/BUILD, scip_indexer/Debug.h, scip_indexer/SCIPIndexer.cc
=> cleanup: Simplify code + add/update doc comments.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/alias.snapshot.rb, test/scip/testdata/args.snapshot.rb, test/scip/testdata/blocks_lambdas_procs.snapshot.rb, test/scip/testdata/cattr.snapshot.rb, test/scip/testdata/classes.snapshot.rb, test/scip/testdata/def_delegator.snapshot.rb, test/scip/testdata/delegate.snapshot.rb, test/scip/testdata/encrypted_prop.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/flatfile_dsl.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/inheritance.snapshot.rb, test/scip/testdata/loops_and_conditionals.snapshot.rb, test/scip/testdata/mattr.snapshot.rb, test/scip/testdata/method_inheritance.rb, test/scip/testdata/method_inheritance.snapshot.rb, test/scip/testdata/minitest.snapshot.rb, test/scip/testdata/multifile/basic/def_class1.snapshot.rb, test/scip/testdata/multifile/basic/use_class1.snapshot.rb, test/scip/testdata/multifile/typed-false-mix/use_untyped.snapshot.rb, test/scip/testdata/prop.snapshot.rb, test/scip/testdata/rescue.snapshot.rb, test/scip/testdata/singleton.snapshot.rb, test/scip/testdata/struct.snapshot.rb, test/scip/testdata/test_case.snapshot.rb, test/scip/testdata/type_change.snapshot.rb
Issa bug.
Added new test, updated existing tests.
=> fix: Fix missing references for non-overriden methods.

core/GlobalState.cc, core/GlobalState.h, resolver/resolver.cc, scip_indexer/SCIPIndexer.cc, test/scip/testdata/field_inheritance.rb, test/scip/testdata/field_inheritance.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/inheritance.snapshot.rb, test/scip/testdata/type_change.snapshot.rb
Right now, go-to-def and find references doesn't quite work properly with inheritance. This is one step towards fixing that for fields. The current approach doesn't work for mixins, only for classes.
New tests for:
=> fix: Fix occurrences for field inheritance

scip_indexer/BUILD, scip_indexer/Debug.cc, scip_indexer/Debug.h, scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPSymbolRef.cc, scip_indexer/SCIPSymbolRef.h
Consistent naming + debugging.
=> cleanup: Clean up Debug.h + add helper function.

scip_indexer/SCIPIndexer.cc, test/scip/testdata/globals.rb, test/scip/testdata/globals.snapshot.rb
=> fix: Fix defs+refs for globals.

proto/SCIP.proto
To enable #116.
Additive change/covered by existing tests.
=> chore: Bump scip dependency for Relationship.is_definition.

test/scip_test_runner.cc
=> test: Slightly simplify loop.

scip_indexer/BUILD, scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPProtoExt.cc, scip_indexer/SCIPProtoExt.h, test/scip/testdata/blocks_lambdas_procs.snapshot.rb, test/scip/testdata/cattr.snapshot.rb, test/scip/testdata/def_delegator.snapshot.rb, test/scip/testdata/encrypted_prop.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/flatfile_dsl.snapshot.rb, test/scip/testdata/mattr.snapshot.rb, test/scip/testdata/minitest.snapshot.rb, test/scip/testdata/prop.snapshot.rb, test/scip/testdata/struct.snapshot.rb
Deterministic snapshot output for testing.
=> fix: Sort while outputting for determinism.

scip_indexer/SCIPProtoExt.cc, test/scip/testdata/args.snapshot.rb, test/scip/testdata/blocks_lambdas_procs.snapshot.rb, test/scip/testdata/cattr.snapshot.rb, test/scip/testdata/def_delegator.snapshot.rb, test/scip/testdata/encrypted_prop.snapshot.rb, test/scip/testdata/field_inheritance.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/flatfile_dsl.snapshot.rb, test/scip/testdata/for.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/mattr.snapshot.rb, test/scip/testdata/prop.snapshot.rb, test/scip/testdata/struct.snapshot.rb
The logic was incorrect earlier.
Manually tested by diffing the index generated after running multiple times.
=> fix: Fix incorrect comparison logic

scip_indexer/BUILD, scip_indexer/Debug.h, scip_indexer/SCIPFieldResolve.cc, scip_indexer/SCIPFieldResolve.h, scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPProtoExt.cc, scip_indexer/SCIPProtoExt.h, scip_indexer/SCIPSymbolRef.cc, scip_indexer/SCIPSymbolRef.h, test/scip/testdata/field_inheritance.rb, test/scip/testdata/field_inheritance.snapshot.rb, test/scip/testdata/fields_and_attrs.snapshot.rb, test/scip/testdata/freeze_constants.snapshot.rb, test/scip/testdata/globals.rb, test/scip/testdata/globals.snapshot.rb, test/scip/testdata/hoverdocs.snapshot.rb, test/scip/testdata/inheritance.snapshot.rb, test/scip/testdata/mixin.rb, test/scip/testdata/mixin.snapshot.rb, test/scip/testdata/type_change.snapshot.rb, test/scip_test_runner.cc
Mixins are used very frequently. We should have better code nav for them.
```ruby
module M
def set_f_0
@f = 0
end
end
class C
def set_f_1
@f = 1
end
end
class D < C
include M
def get_f
@f
end
end
```
The code is currently set up so that:
1. The reference inside a class will emit a symbol for the further ancestor which mentions the class. (However, strictly speaking, we don't require a definition inside that ancestor's body right now... -- but it would be strange for a superclass to access a field that it never sets, so...). In this case, the occurrence for `@f` in `get_f` will use `C#@f`. (← Not sure if this is a good idea though, see next point.)
2. We emit a reference relationship for symbols that are mentioned (transitively) in mixins when emitting the _definition_. In this case, there …
=> fix: Add support for unresolved fields from mixins

scip_indexer/SCIPIndexer.cc, test/scip/testdata/blocks_lambdas_procs.rb, test/scip/testdata/blocks_lambdas_procs.snapshot.rb
Triggered when trying to index Homebrew/brew.
Added test crashes without this patch.
=> fix: Fix crash with defaulted lambda parameters.

main/pipeline/pipeline.cc, test/scip/testdata/typed_false.rb, test/scip/testdata/typed_false.snapshot.rb
Fixes #30. We still need to do extra error suppression (https://github.com/sourcegraph/scip-ruby/issues/131), will do that in a follow-up PR instead of bundling it here.
Everything else is unchanged, so only going with a small test case for now.
=> feat: Index `# typed: false` files by default

docs/scip-ruby/CONTRIBUTING.md, scip_indexer/SCIPIndexer.cc, tools/scripts/publish-scip-ruby.sh
Fixes #127.
Manually tested the output.
=> fix: Print scip-ruby version, not Sorbet version.

README.md
You get an error otherwise. Tweaked from #88.
Tested manually.
=> docs: Mention path argument in README.

README.md, scip_indexer/SCIPIndexer.cc
Simplifies the invocation, the `--index-file` is kinda' not terribly useful for most people.
Tested manually against `shopify-api-ruby`.
=> fix: Use default --index-file argument for convenience.

.github/workflows/ci.yml, README.md, common/FileOps.h, common/FileSystem.cc, common/FileSystem.h, common/common.cc, docs/scip-ruby/CONTRIBUTING.md, main/pipeline/pipeline.cc, main/pipeline/semantic_extension/SemanticExtension.h, plugin_injector/plugin_injector.cc, scip_indexer/Debug.h, scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPSymbolRef.cc, scip_indexer/SCIPSymbolRef.h, test/helpers/MockFileSystem.cc, test/helpers/MockFileSystem.h, test/scip/scip_test.bzl, test/scip_test_runner.cc
This will be useful for auto-indexing because we'd like the indexer to infer the Gem name and version instead of having it be input from the command-line (the logic needs to live _somewhere_, so it might as well live in the indexer).
TODO:
Tested manually against shopify-api-ruby. I will add some automated tests.
=> fix: Try to infer gem name and version.

scip_indexer/BUILD, scip_indexer/SCIPGemMetadata.cc, scip_indexer/SCIPGemMetadata.h, scip_indexer/SCIPIndexer.cc, scip_indexer/SCIPSymbolRef.cc, scip_indexer/SCIPSymbolRef.h, test/scip_test_runner.cc
This will serve as the right place to put the logic for file-to-gem maps etc.
=> chore: Move gem metadata logic into separate TU.

README.md, docs/scip-ruby/CLI.md, docs/scip-ruby/CONTRIBUTING.md
Add central place for documenting all flags. For the building from source,
it was missed earlier, and we may not have published a release, so pointing it out explicitly is useful.
n/a
=> docs: Add docs for CLI and building from source.

core/GlobalState.cc, core/GlobalState.h, main/options/options.cc, main/options/options.h, main/options/test/options_test.cc, main/realmain.cc
We could submit a patch for this upstream?
n/a, this is a debugging flag.
=> feat: Add flag for debugging recorded file paths.

test/helpers/expectations.cc, test/scip/scip_test.bzl, test/scip/testdata/multifile/gem-map/gem-map.json, test/scip/testdata/multifile/gem-map/scip-ruby-args.rb, test/scip_test_runner.cc
The next thing to do is add tests for special paths like sorbet/rbi/gems,
so it will be useful to make sure that we cd to the 'project root' similar
to how scip-ruby will actually run in practice.
=> cleanup: Use test-relative paths by cd-ing before testing.

docs/scip-ruby/CLI.md, scip_indexer/SCIPGemMetadata.cc, scip_indexer/SCIPGemMetadata.h, test/scip/testdata/multifile/infer-gem-map/current_gem.rb, test/scip/testdata/multifile/infer-gem-map/current_gem.rbi, test/scip/testdata/multifile/infer-gem-map/current_gem.snapshot.rb, test/scip/testdata/multifile/infer-gem-map/current_gem.snapshot.rbi, test/scip/testdata/multifile/infer-gem-map/scip-ruby-args.rb, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/annotations/annotgem.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/annotations/annotgem.snapshot.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/dsl/railsgem.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/dsl/railsgem.snapshot.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/gems/extgem@99.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/gems/extgem@99.snapshot.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/hidden-definitions/hidden.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/hidden-definitions/hidden.snapshot.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/todo.rbi, test/scip/testdata/multifile/infer-gem-map/sorbet/rbi/todo.snapshot.rbi, test/scip_test_runner.cc
This should make it easier to set up cross-repo code nav.
=> feat: Infer gem info from standard filesystem layout.

CHANGELOG.md, scip_indexer/SCIPIndexer.cc
=> docs: Add CHANGELOG entry for v0.3.0

.github/workflows/publish-docker.yml, .github/workflows/release.yml, Dockerfile.autoindex, docs/scip-ruby/CONTRIBUTING.md, scip_indexer/autoindex.sh, tools/scripts/publish-scip-ruby.sh
Add a Dockerfile + publishing workflow for autoindexing. Partial progress towards https://github.com/sourcegraph/sourcegraph/issues/44122
TODOs:
Manually tested the image. Running `scip-ruby-autoindex --gem-name blah --gem-version blah` with an optional `--is-package` does the trick.
=> feat: Add Docker image for auto-indexing support.

scip_indexer/autoindex.sh
Fixes #164.
Manually tested against github/linguist.
=> autoindex: bundle install for non-Sorbet code before autoindexing.

third_party/doctest.BUILD
=> chore: Silence build warning for newer macOS SDKs.

.github/workflows/build_gems.yml, .github/workflows/release.yml
The latter is deprecated/archived now
Will run the Check Gem Build action manually.
=> ci: Use ruby/setup-ruby instead of actions/setup-ruby

CHANGELOG.md, Dockerfile.autoindex, scip_indexer/SCIPIndexer.cc
Bundler allows git-based Gem dependencies, so it needs access to
a `git` binary while running. https://bundler.io/guides/git.html
Manually checked that adding `git` fixes the error Bundler runs into.
=> autoindex: Bundle git in Docker image

.github/workflows/build_gems.yml, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/publish-docker.yml, .github/workflows/publish-manual.yml, .github/workflows/release.yml
GitHub recently changed 'ubuntu-latest' to mean Ubuntu 22.04
but that breaks the build due to libtinfo5 not being
installed. We can fix it later...
Run CI
=> ci: Use Ubuntu 20.04 and macOS 12 in CI

scip_indexer/SCIPIndexer.cc
I forgot to update it in #175
n/a
=> fix: Update SHA for upstream Sorbet

gems/scip-ruby/BUILD
The gem build uses old constraints which are no longer applicable.
Tested here: https://github.com/sourcegraph/scip-ruby/actions/runs/5263217577/jobs/9513161898
=> build: Use platform constraints in gem builds

scip_indexer/SCIPIndexer.cc
Fixes #180.
I can't quite tell when this is triggered, and I haven't been
able to reproduce the issue with other OSS projects,
but the extra check should avoid the assertion being hit.
=> fix: Avoid assertion in asSymbolRef()

docs/scip-ruby/CONTRIBUTING.md
=> docs: Fix broken links to Sorbet README

core/GlobalState.h, resolver/resolver.cc, scip_indexer/SCIPFieldResolve.cc
I'm not exactly sure why, but the result in `unresolvedFields` (after name resolution
is complete) is non-deterministic. This means that a field may show up as unresolved
in the class in one run, and resolved in another run.
Thus, if the class K is present as a key in `unresolvedFields` but doesn't have a
corresponding value for a field `@v`, it may just be an artifact of the run.
As such, we can continue with the normal path of name lookups, rather
than having a fast path for this edge case, with a potentially misleading diagnostic.
n/a
=> fix: Remove incorrect diagnostic for unknown field

scip_indexer/SCIPIndexer.cc
It's untyped code, it is not too surprising if it is missing type information...
n/a
=> fix: Skip missing type info log message in untyped code

scip_indexer/SCIPIndexer.cc
For very large monorepos, one might hit the Protobuf 2GB message limit size
with the default generated C++ code. Bypass the limit by streaming the output,
similar to scip-clang.  https://github.com/sourcegraph/scip-clang/pull/256
Tested that code nav continues to work for shopify-api-ruby.
=> fix: Output documents in a streaming fashion to avoid 2GB limit

scip_indexer/SCIPIndexer.cc, test/scip/testdata/functions.rb, test/scip/testdata/functions.snapshot.rb
=> fix: Remove assertion due to multiple locals at same location

scip_indexer/SCIPIndexer.cc
Fixes #193
Unable to reproduce yet, no tests available.
=> fix: Short-circuit on empty locations for locals

scip_indexer/SCIPIndexer.cc
Fixes #203
n/a, it's simple enough
=> fix: Add extra slash in URI for project root
